version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build started on `date`
      # - cd backend
  build:
    commands:
      - echo Build started on `date`
      - python --version
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p ~/.ssh
      - aws s3 cp s3://john-terraform-state-bucket-002/jbaba-key.pem ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ls
      - echo Copying files to server...
      - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r backend/* ubuntu@34.205.43.1:app
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@34.205.43.1 "sudo apt-get update -y && sudo apt-get install -y python3-venv && python3 -m venv app/venv && source app/venv/bin/activate && pip install --upgrade pip && pip install -r app/requirements.txt && python3 app/src/server.py"
